api/class-aftership-api-orders.php, api/class-aftership-api-server.php
modified:   api/class-aftership-api-orders.php
modified:   api/class-aftership-api-server.php
=> added methods for Postmen Woocommerce store connector

api/class-aftership-api-orders.php
modified:   api/class-aftership-api-orders.php
=> enable order note

aftership.php, class-aftership-settings.php
=> custom domains and required field updates

aftership.php, assets/js/admin.js, assets/js/footer.js, readme.txt
https://aftership.atlassian.net/browse/AS-3708
Do not merge yet:
Can we deploy this to our testing store first, and test more there?
=> [AS-3708] remove setTimeout, use 'in_admin_footer' hook instead

assets/js/couriers.js
https://aftership.atlassian.net/browse/AS-4675
=> [AS-4675] update list of couriers

api/class-aftership-api-orders.php
https://aftership.atlassian.net/browse/AS-5461
=> [AS-5461]added support for new plugin

assets/js/couriers.js
https://aftership.atlassian.net/browse/AC-132
=> [AC-132] courier not available in woocommerce - allied express.

assets/js/couriers.js
https://aftership.atlassian.net/browse/AC-286
@davidNHK
=> [AC-286] Courier not available in Woocommerce-tcs.

aftership-backward-compatibility.php, aftership-functions.php, aftership.php, api/class-aftership-api-orders.php, readme.txt
https://aftership.atlassian.net/browse/AC-121
=> [AC-121] WooCommerce error

assets/js/couriers.js
https://aftership.atlassian.net/browse/AC-388
=> [AC-388] Add courier TIPSA into woo plugin

assets/js/couriers.js
https://aftership.atlassian.net/browse/AC-820
=> [AC-820] Add omniva & pilot-freight into Woocommerce

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-867
https://aftership.atlassian.net/browse/AC-868
=> [AC-867, AC-868] Add couriers

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-911
https://aftership.atlassian.net/browse/AC-915
=> [AC-911, AC-915]

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-1169
=> [AC-1169] Add courier ZTP Express

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-1389
=> [AC-1389] Update Couriers for Woocommerce plugin

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-1707
=> [AC-1707] Update Woocommerce plugin couriers

api/class-aftership-api-orders.php
https://aftership.atlassian.net/browse/AC-1824
=> [AC-1824] Import custom field from woocommerce order

aftership.php, assets/js/couriers.js, readme.txt
https://aftership.atlassian.net/browse/AC-2018
=> [AC-2018] Update courier list

aftership.php, readme.txt
[CNT-6459] Update video link
[CNT-6459]: https://aftership.atlassian.net/browse/CNT-6459
=> [CNT-6459] Update video link

aftership.php, readme.txt
[CNT-6515] Update plugin name && tags && description
[CNT-6515]: https://aftership.atlassian.net/browse/CNT-6515
=> [CNT-6515] Update plugin name && tags && description

aftership.php, readme.txt
Update version number keep same as svn
=> Update version number keep same as svn

aftership.php, assets/js/couriers.js, readme.txt
[CNT-6951] Update courier name for australia-post-api
[CNT-6951]: https://aftership.atlassian.net/browse/CNT-6951
=> [CNT-6951] Update courier name for australia-post-api

aftership-woocommerce-tracking.php, assets/css/admin.css, assets/js/meta-box.js, includes/class-aftership-actions.php
这里增加了一个基本的编辑功能
但是存在已知问题
编辑完成之后保存，其实是创建了一条新的tracking (没有删除编辑前的记录)
=> [CNT-6970] Add feature for edit tracking

assets/css/admin.css, assets/js/meta-box.js, includes/class-aftership-actions.php
warn user has un-save content when form already shown
=> :bug: [ABU-7754]: fix same shipment validation

aftership-woocommerce-tracking.php, includes/class-aftership-actions.php, readme.txt
[CNT-7408] Fix issue for generate API key
[CNT-7408]: https://aftership.atlassian.net/browse/CNT-7408
=> [CNT-7408] Fix issue for generate API key

aftership-woocommerce-tracking.php, assets/js/setting.js, includes/class-aftership-settings.php, readme.txt
[CNT-7589] Fix some plugin conflict issue
[CNT-7589]: https://aftership.atlassian.net/browse/CNT-7589
=> [CNT-7589] Fix some plugin conflict issue

aftership-woocommerce-tracking.php, includes/class-aftership-actions.php, readme.txt
[CNT-7859] Fix tracking missing when update plugin
[CNT-7859]: https://aftership.atlassian.net/browse/CNT-7859
=> [CNT-7859] Fix tracking missing when update plugin.

aftership-woocommerce-tracking.php, includes/api/v4/class-aftership-api-settings.php, includes/class-aftership-actions.php, includes/class-aftership-settings.php, readme.txt
[CNT-7928] Fix tracking button url issue
[CNT-7928]: https://aftership.atlassian.net/browse/CNT-7928
=> [CNT-7928] Fix tracking button url issue

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, assets/js/setting.js, includes/class-aftership-settings.php, readme.txt
[CNT-8266] Update courier list
[CNT-8266]: https://aftership.atlassian.net/browse/CNT-8266
=> [CNT-8266] Update courier list

aftership-woocommerce-tracking.php, readme.txt
[CNT-8263] Update plugin description
[CNT-8263]: https://aftership.atlassian.net/browse/CNT-8263
=> [CNT-8263] Update plugin description

aftership-woocommerce-tracking.php, readme.txt
[CNT-8263] Update readme
[CNT-8263]: https://aftership.atlassian.net/browse/CNT-8263
=> [CNT-8263] Update readme

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, readme.txt
[CNT-8745] Update courier list
[CNT-8745]: https://aftership.atlassian.net/browse/CNT-8745
=> [CNT-8745] Update courier list

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, includes/api/class-aftership-api.php, includes/api/v5/class-aftership-api-settings.php, readme.txt
[CNT-8900] Update courier list
[CNT-8900]: https://aftership.atlassian.net/browse/CNT-8900
REF
https://docs.google.com/document/d/17oOrelK6I9hPuB4ROz57GLUne-wmPR3fExX_JwOU8Fc/edit
=> [CNT-8900] Update courier list

aftership-woocommerce-tracking.php, composer.lock, includes/api/class-aftership-api-authentication.php, readme.txt
[CNT-9074] Compatible with [Advanced Access Manager]
[CNT-9074]: https://aftership.atlassian.net/browse/CNT-9074
=> [CNT-9074] Compatible with [Advanced Access Manager]

.gitignore, aftership-woocommerce-tracking.php, readme.txt
[CNT-9659] Update listing readme
[CNT-9659]: https://aftership.atlassian.net/browse/CNT-9659
=> [CNT-9659] Update listing readme

aftership-woocommerce-tracking.php
=> Update plugin comment

aftership-woocommerce-tracking.php, readme.txt, views/automizely_aftership_on_boarding_view.php, views/automizely_aftership_setting_view.php
[CNT-9660] fix OAuth link issue
[CNT-9660]: https://aftership.atlassian.net/browse/CNT-9660
=> [CNT-9660] fix OAuth link issue

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, readme.txt
[CNT-10798] Update courier list
[CNT-10798]: https://aftership.atlassian.net/browse/CNT-10798
=> [CNT-10798] Update courier list

aftership-woocommerce-tracking.php, includes/api/class-aftership-api.php, readme.txt
=> report error on debug mode 

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, includes/api/aftership/v1/class-am-rest-settings-controller.php, includes/class-aftership-actions.php, readme.txt
Add modified_after & modified_before filter for customers
=> Add modified_after & modified_before filter for customers

aftership-woocommerce-tracking.php, includes/api/aftership/v1/class-am-rest-settings-controller.php, readme.txt
Add some fields for settings API
=> Add some fields for settings API

aftership-woocommerce-tracking.php, assets/js/couriers.js, assets/js/couriers.json, readme.txt
=> Update courier list

aftership-woocommerce-tracking.php, includes/class-shipment-tracking-migrator.php, readme.txt
=> Update tracking migrate cron

aftership-woocommerce-tracking.php, readme.txt
升级到 1.17.17
原因
1.17.16 版本发布的时候，没有生成到文件，导致有问题。插件是还是历史版本 1.17.15，不影响业务。处理好后，重新处理的时候说 1.17.16
=> [CNT-34449] change version 1.17.17
